server:
  port: 8300
  #servlet.context-path: /user-service
  #servlet.context-path: /${spring.application.name}

#user-service:
  #user.fetchLimit:  300

eureka:
  client:
    registerWithEureka: true
    fetchRegistry:  true
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
    healthcheck:
      enabled:  true