server:
  port: 8080

servlet.context-path: /gateway-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry:  true
    serviceUrl:
      defaultZone:  http://localhost:8761/eureka/
    healthcheck:
      enabled:  true

ribbon:
  ReadTimeout: 60000

zuul:
  ignoredServices:  '*'
  #ignoredServices helps to avoid any services automatically added
  sensitiveHeaders: Cookie,Set-Cookie,Authorization
  #It is blacklist. Zuul does not send it to the downstream services
  #sensitiveHeaders: (If you want to allow all the headers, need to add an empty list like this)
  routes:
    user:
      path: /user-service/**
      serviceId:  user-service
      stripPrefix:  false
  maxTotalConnections:  200
  maxPerRouteConnections: 20
