server:
  port: 8200
  servlet.context-path: /notification-service
  #servlet.context-path: /${spring.application.name}

#user-service:
#  context-path: /user-service
#  ribbon:
#    eureka.enabled: false
#    listOfServers:  http://localhost:8300,http://localhost:8301/,http://localhost:8302
#    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
#    ServerListRefreshInterval:  15000
#    MaxAutoRetries: 2
#    ReadTimeout:  5000


#ribbon.eureka.enabled: false

#logging.level:
  #com.loriini.notification.client.UserServiceClient:  DEBUG

feign:
  client.config.default.loggerLevel: full

eureka:
  client:
    registerWithEureka: true
    fetchRegistry:  true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/